### ISSUE TITLE
Add support for TLS  connection from App to Proxy

### ISSUE THREAD

**Issue by munnerz** [GoogleCloudPlatform/cloudsql-proxy#102]
Hi there

I'm deploying a large microservices application onto Kubernetes. End-to-end encryption between pods is a requirement, and so we're looking to use TLS whenever data may be transmitted between applications.

Both MySQL and PostgreSQL support TLS for secure connections (https://dev.mysql.com/doc/refman/5.7/en/secure-connections.html & https://www.postgresql.org/docs/9.1/static/ssl-tcp.html). Would it be possible for cloudsql-proxy to support this same TLS protocol too?

Due to the lack of support for secure connections between application and proxy, I'm forced to deploy the proxy as a sidecar container in every application pod - potentially hundreds of instances could be running at one time!

Is there any plan to support secure connections to the proxy in future?

**Comment by Carrotman42** [comment]
There is no current plans to support this. If you're already going through
the trouble to deal with SSL, you can just configure your cloud SQL
database to require SSL for connectivity and open the firewall up. Why do
you need to doubly encrypt?

Does the Proxy have too much overhead to ship it as a sidecar? Last I
checked, it had a very low minimum footprint (< 5MBs) and only uses memory
in proportion to the number of active connections through the proxy. If it
is too much overhead, please describe the amount of overhead that is "too
much" and maybe we can come up with another plan. (Maybe it's the CPU you
care about?)

One thing to note: having a single Proxy binary that all clients connect to
can easily become a very large bottleneck if you're not careful. Keeping
the proxy as a sidecar allows loopback connectivity between the Proxy and
your application which usually results in a large latency reduction.

**Comment by munnerz** [comment]
Thanks for getting back to me -

So regarding your first point of opening the firewall up, my issue is that I'm running on GKE and so would need to run some kind of daemon on each node that has permission to update the SQL instance to grant each node access to the cluster. Then, if that were done, I could skip out the proxy altogether as you say.

It doesn't have too much overhead, however I am managing 15 microservices each needing access to cloud SQL, and each running a number of replicas so it does result in quite a lot of extra containers, and management overhead keeping config for the proxy in sync!

I wasn't intending to have a single proxy instance running, rather say a pool of 3. Each application could then connect to any one of those instances - I could then create an autoscaler on those instances, so they can be scaled up if traffic grows!

**Comment by mykolasmith** [comment]
Just run cloudsql-proxy as its own container in each pod. That way, your application pods can communicate to it over localhost and you don't need to expose your proxy across your cluster.

```
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.10
        command: [
          "/cloud_sql_proxy",
          "--dir=/cloudsql",
          "-instances={{.project}}:us-east1:metadata-1=tcp:5432",
          "-credential_file=/secrets/cloudsql/credentials.json",
          "-quiet"
        ]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: cloudsql
          mountPath: /cloudsql
```

**Comment by Carrotman42** [comment]
@munnerz on your point about having 15 microservices: is there no other thing which needs to be shared among all of these microservices? I was thinking that you'd have a single configuration for a generic Cloud SQL Proxy container and somehow share that across all of your services. I don't use Kubernetes, so I'm not sure if that's particularly easy, but it seems like creating an autoscaling pool of Proxy containers and dealing with that would be more complex and more work to support than simply sharing the configuration among all of the microservices via some templating, build-time rule, or other automated process.

Alternatively, does @mykolasmith's suggestion work for you, or is that basically the configuration you are having trouble sharing?

**Comment by Carrotman42** [comment]
Any updates here?

**Comment by mykolasmith** [comment]
Quick addendum to my previous response. We've found that running a ton of cloudsql-proxy containers in each pod results in a lot of overhead and extraneous connections to the database. We've replaced this with a single pod / service running two containers: 1) cloudsql-proxy and 2) pgbouncer (https://pgbouncer.github.io/). We now have a single service that pools all connections to the Google Cloud SQL. All of our microservices connect to this service, rather than co-hosting their own dedicated cloudsql-proxy.

**Comment by J-Rojas** [comment]
Supporting full encryption on both ends of the proxy would ensure compliance with architectures the require 'encryption in transit' such as HIPAA. Currently the only way to fulfill this requirement is by guaranteeing the proxy connection is never between two nodes, and the only way to guarantee that on GKE is to 'sidecar' your proxy with your application into one pod. Pods are the only workload that is atomic and is guaranteed to run on a local network and a local machine. Containers outside of a Pod can be reallocated to different nodes in your cluster. Others have mentioned how inefficient this across a microservice architecture since the proxy has to be cloned several times. I think the only workaround for this is to make use `socat` with an SSL tunnel, but that would incur multiple steps of encryption/decryption between pods/containers. It would be best to support the encryption directly in the proxy so it is as transparent an integration as possible.

**Comment by Carrotman42** [comment]
Is it actually that inefficient to have multiple copies of the Proxy, one
per pod? Can someone show that this is actually a problem with specific
benchmark/production data?

**Comment by ohaiwalt** [comment]
Any movement here? Just ran into this while evaluating GKE for new workloads. It would be ideal to configure the cloudsql-proxy in the way that @munnerz described as a separate service to handle connections.

**Comment by enocom** [comment]
Related to https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/242.

**Comment by enocom** [comment]
Adding TLS support to the proxy introduces a requirement for protocol-level knowledge for the three supported databases, which in turn introduces a significant amount of complexity that doesn't seem worth the cost in this case. 

I do understand the importance of "encryption in transit" as @J-Rojas points out above. As a workaround, we recommend running the proxy locally (either via a unix socket or a TCP socket on localhost) and using file permissions or iptables to secure access. If for some reason this isn't feasible, we recommend pairing the proxy with a more specialized connection pooling proxy that can support SSL/TLS, which will lead to better overall performance. For instance, see pgbouncer or pgpool.
