### ISSUE TITLE
Cloud Sql Proxy on same instance for 2 SQL servers

### ISSUE THREAD

**Issue by daljeet-singh** [GoogleCloudPlatform/cloudsql-proxy#107]
Hi, how to enable cloud proxy on same server for 2 different sql instances ( master, slave ) or how to define custom ip address for host.

I dont want to use different port for different connections, can we use different ip addresses?

**Comment by Carrotman42** [comment]
Why don't you want to use a separate port for each instance?

I believe it is possible to use a different loopback IP address instead of
different ports (on the same loopback IP address) but I've never done it
and I don't know how. You can search the web for how to set up a multiple
local IPs on the same computer for your OS. Once you have multiple IPs,
using them should be something like:

    --instances=project:region:instance1=tcp:IP_ADDRESS1:PORT,project:
region:instance2=tcp:IP_ADDRESS2:PORT

**Comment by Carrotman42** [comment]
Any thoughts here? Is there anything I can do to help?
