### ISSUE TITLE
Cannot connect to MySQL if -enable_iam_login is passed

### ISSUE THREAD

**Issue by alamothe** [GoogleCloudPlatform/cloudsql-proxy#1318]
## Bug Description

We have a MySQL 5.7 instance. After the latest maintenance event on Aug 20, 2022, it was not possible to connect to this instance using Cloud SQL Proxy. The errors were:

SQL error logs showed: "Got an error reading communication packets"
From proxy side: "Connection lost: The server closed the connection."

When I tried to use MySQL Workbench it showed: "Lost connection to MySQL server at 'reading authorization packet', system error: 35"

After lots of debugging, it turned out that the problem is with `-enable_iam_login` flag. After removing this flag, everything was working again.

Please note:
- Previously (before the maintenance event), this flag caused no issues.
- We use this flag because we connect to multiple instances, some of which are PostgreSQL, and they require it.

## Example code (or command)

```
cloud_sql_proxy -instances=ridemycar-1483775910341:us-central1:freesync-001=tcp:3307 -enable_iam_login
```

## Stacktrace
```
2022/08/22 10:43:26 Scheduling refresh of ephemeral certificate in 59m3s
2022/08/22 10:43:26 Instance ridemycar-1483775910341:us-central1:freesync-001 closed connection
2022/08/22 10:43:26 Instance ridemycar-1483775910341:us-central1:freesync-001 closed connection
2022/08/22 10:43:26 Instance ridemycar-1483775910341:us-central1:freesync-001 closed connection
2022/08/22 10:43:26 Instance ridemycar-1483775910341:us-central1:freesync-001 closed connection
```

## How to reproduce

  1. Start Cloud SQL Proxy to connect to MySQL 5.7 instance with `-enable_iam_login`
  2. Try to connect to the instance

## Environment

1. OS type and version: MacOS M1 Pro
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): `Cloud SQL Auth proxy: 1.31.2+darwin.arm64`

The above is on my dev machine, but the same result was on Kubernetes.

**Comment by enocom** [comment]
Thanks for the report @alamothe. I suspect this is a recent backend change breaking the proxy. I'll investigate and report back here.

**Comment by enocom** [comment]
After some digging, I see that there's a recent change in the MySQL backend that brought this about.

In short, the proxy should have been throwing an error when it was invoked with a mix of Auto IAM authn Postgres instances and regular authn MySQL instances. To support multiple instances like this, I'm afraid you'll have to start a different instances of the proxy: one for the IAM authn instances, one for the regular authn instances.

At the very least, we've fixed this in the v2 version of the proxy where you'll be able to opt-in to Auto IAM AuthN on a per instance basis. If you wanted to try that out you'd have to build a binary from the v2 branch. We'll be publishing binaries of v2 soon otherwise.

**Comment by enocom** [comment]
Related to https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/283.

**Comment by alamothe** [comment]
Makes sense, thanks for looking into this.
