### ISSUE TITLE
SQL syntax error when using proxy library, but works with external proxy - GCS postgres 9.6

### ISSUE THREAD

**Issue by SandyWalsh** [GoogleCloudPlatform/cloudsql-proxy#153]
When I use the postgres builtin golang proxy I get an error attempting to prepare statements. Like

`INSERT INTO "snapshot" (uow_id,group_id,name,state,user_id,org_id,last_change,locked,lock_time,poll_at,last_message,data,created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING uow_id`  

```
dsn = "host=project:region:instance dbname=postgres user=postgres password=foo sslmode=disable"

db, err := sqlx.Open("cloudsqlpostgres", dsn)
if err != nil {
	return nil, err
}

x, err := p.db.Preparex(p.db.Rebind(s))
if err != nil {
	panic(err)
}
```

`syntax error at or near "," at character 143"`
which is the  `(?,` part

... but this works fine without the proxy (and local postgres). And it works with the external postgres proxy. 

I would have assumed the external proxy was the same code as the internal proxy.

So I can only guess the difference is the form of connection string I'm using. 

With the external proxy I'm using URI format
`postgres://postgres@localhost:5432/postgres?password=foo&sslmode=disable`

and that's fine

**Comment by Carrotman42** [comment]
Can you post a small, compilable, and self-contained code example of the
thing that isn't working? From the code you pasted, it's impossible for me
to tell if the problem is actually coming from the `sqlx` package (whatever
that is), the call to `Rebind` with mystery parameter `s`, etc, or
something in the Proxy stack.

Note: the Proxy does not have any understanding of the underlying database
protocol, so I'm guessing it could not cause the problem you're describing.
Sounds like some bug in another part of your application, but of course I'm
not certain without a self-contained repro.

**Comment by SandyWalsh** [comment]
Thanks @Carrotman42 ... fair point. Lemme try to pull something together for you.

**Comment by SandyWalsh** [comment]
Ah ha ... figured it out. 

sqlx.Rebind() converts ? to the appropriate placeholder of the db. 

With the built-in proxy, it's cloudsqlpostgres and sqlx doesn't recognize that. So it keeps it as ? ... but postgres wants $1, $2, $3, etc.

Which explains why the external proxy works ... the driver is still "postgres"

Sorry for the false alarm.
