### ISSUE TITLE
Graceful shutdown to stop creating error messages in cloudsql log

### ISSUE THREAD

**Issue by tom932** [GoogleCloudPlatform/cloudsql-proxy#192]
Currently, I have services running in Kubernetes. Those services use a cloudsql-proxy as sidecar container.
However, when I release a new version of a service, or just restart it by calling `kubectl delete pod PODNAME`, the cloudsql-instance logs the following error message:

```
Aborted connection 101566 to db: 'DB_NAME' user: 'USERNAME' host: 'cloudsqlproxy~IPADDRESS' (Got an error reading communication packets)
```

The error is also mentioned in https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/126 , but I don't think it is related, since we do not have the metioned memory leak, but want to supress the warning.

I guess it makes sense that the message is logged, since the pod and its containers are removed, and therefore an existing connection is aborted. 

However, is there a way to stop this log message when the shutdown of the pod is planned? Can I gracefully shut down the sidecar container first, so no message is produced?

Is there any other way, or do I have to accept those messages?

**Comment by kurtisvg** [comment]
You may be interested in #178.

Leaving this open for now, but probably a duplicate.

**Comment by hfwang** [comment]
#178 is definitely a potential fix.

However, in order to really get rid of those messages, you should ideally allow your application server to drain when `kubectl delete pod` is called, so that your application can close the connections cleanly. Otherwise the database server has to be the one noticing that there is no more traffic on a connection.
