### ISSUE TITLE
Google cloud sql proxy using wrong ssl cert to to establish socket connection with failover

### ISSUE THREAD

**Issue by johnnie502** [GoogleCloudPlatform/cloudsql-proxy#256]
We have a production system that connect to Cloud SQL with failover via Cloud SQL Proxy. On Feb 13 the database was down for a few moments in which the failover should have kicked in but it didn't:

```
2019/02/13 20:15:47 couldn't connect to "project-id:us-central1:project-name": x509: certificate is valid for project-id:us-central1:project-name-failover, not project-id:us-central1:project-name

2019/02/13 20:15:47 Throttling refreshCfg(project-id:us-central1:project-name): it was only called 316.152967ms ago

2019/02/13 20:15:47 couldn't connect to "project-id:us-central1:project-name": x509: certificate is valid for project-id:us-central1:project-name-failover, not project-id:us-central1:project-name
```

From the error message it looks like that proxy connect to the main db with the failover ssl, or vice versa. Since we can't tweak the ssl configuration for the proxy (seems it's managed by the back-end), it's hard to debug or reproduce the issue.

This is similar to #34 that has the solution to reset the ssl certification, however might not work for this case.

**Comment by kurtisvg** [comment]
Hi @johnnie502,

Can you clarify by what you mean by failover? Do you have high availability enabled for the Cloud SQL instance?  Is it Postgres or MySQL?

**Comment by johnnie502** [comment]
Hi @kurtisvg 

This is our setup
![image](https://user-images.githubusercontent.com/1442600/53742448-3e9f8380-3e5e-11e9-8b4f-d01c27b7ecf6.png)

It's MySQL 2nd Gen with failover

**Comment by kurtisvg** [comment]
@johnnie502 - Did you attempt to connect to the failover directly, or did the primary instance fail and cause the second instance to become promoted?

**Comment by johnnie502** [comment]
@kurtisvg We haven't try to manually connect to the failover. The error appears in the application logs. I've also created ticket on buganizer-system@google.com. The engineer said he didn't see any downtime of both db instance. I am wondering maybe there was connectivity issue so the application instance (hosted in app engine flex) or the cloud sql proxy decided to switch the instance to failover, but seems using the wrong ssl certs.

However we don't see any more error after that. Since this is our production site, we prefer not to do experimentation on live. Do you have any other suggestions?

**Comment by kurtisvg** [comment]
After some consultation with the connectivity team, it appears this is a side effect of the way the failover process occurs. Sometimes the primary becomes unresponsive and traffic will be sent to the failover before a full failover takes effect. 

You can safely ignore these errors without any concern.

**Comment by steshaw** [comment]
I came here because we experienced this issue just a moment ago. We have a high availability set up also. It doesn't look like the primary database was down. We have two replicas of Cloud SQL proxy in GKE and they looked to be getting hammered. We did encounter downtime in our origin domains but fortunately operating behind a CDN.

I don't want to simply ignore these errors. Is there something we can do? I'm curious why cloudsql-proxy tries to failover when the primary database appears to be up.

We are using the `gcr.io/cloudsql-docker/gce-proxy:1.09`image.

**Comment by Carrotman42** [comment]
As I understand it, it's a backend problem and not something that the cloudsql-proxy process can do anything about. At least, not without some backend/API changes.

**Comment by steshaw** [comment]
We are moving to private IP connectivity to avoid `cloudsql-proxy`. Will that help with these errors since they aren't related to `cloudsql-proxy`?

How can I subscribe to the backend problem that causes this? Perhaps I could vote it up :grin:.

**Comment by kurtisvg** [comment]
IIRC, this issue is caused because the primary instance doesn't respond to the connection attempt, and the load balancer redirects the connection to the failover instance instead. The error occurs because the secondary instance hasn't been promoted (the primary hasn't been unavailable long enough to trigger the failover process). Even if using an authentication method beside the proxy, you'll still get an error and that connection attempt will fail. This is the reason a fix for this hasn't been prioritized - the connection will still fail because the primary instance is unable to handle the connection, and only the error being returned will change.

It's also my understanding that you won't experience this with the version of [HA used for Postgres](https://cloud.google.com/sql/docs/postgres/high-availability), which is going to be available for MySQL soon.

**Comment by steshaw** [comment]
Thanks for the detailed response @kurtisvg. We will have the opportunity to switch from MySQL to Postgres for our CMS down the line. We were probably under an attack since our traffic is typically served by the CDN/Fastly.

**Comment by mehadi92** [comment]
This issue is gone after upgrading from 1.11 to `gce-proxy:1.33.2` version

**Comment by jwh-hutchison** [comment]
> This issue is gone after upgrading from 1.11 to `gce-proxy:1.33.2` version

I had the exact same issue resolved which wasn't happening on my previous cluster. Have you undergone a k8s engine version upgrade lately @mehadi92 ? it might be related to a new version.

**Comment by enocom** [comment]
We've just release a v2. I'd recommend upgrading to latest generally, as there have been numerous bug fixes (and new features) in the latest release.
