### ISSUE TITLE
question - do I need to use this from GCE

### ISSUE THREAD

**Issue by npomfret** [GoogleCloudPlatform/cloudsql-proxy#274]
I have a GCE cluster and am having problems connection directly to my PostgreSQL cloud sql instance:

    Error: unable to get database connection: connect ENOENT /cloudsql/<my-project>:europe-west1:client-data/.s.PGSQL.5432

Do I need to use the proxy to connect from GCE?

**Comment by kurtisvg** [comment]
I'm not sure what you mean by "GCE cluster" - do you mean GKE?

Either way, the proxy is not required for any environment. Other authentication alternatives include using a self-created [SSL/TLS certificate](https://cloud.google.com/sql/docs/mysql/configure-ssl-instance) or [whitelisting](https://cloud.google.com/sql/docs/mysql/configure-ip#add) an IP range.

**Comment by Carrotman42** [comment]
To follow up - it looks like you're trying to use the AppEngine-style path to access a cloudsql instance (i.e. the /cloudsql/ path). GCE VMs do not have the /cloudsql/ filesystem on them by default or anything, but you can "create" that filesystem by starting the proxy on a VM and setting the directory to /cloudsql. Otherwise, you can use the methods that Kurtis linked.

**Comment by npomfret** [comment]
@kurtisvg Google Compute Engine (GCE).  

Thanks for the help.  Connecting to my postgresql cloud sql instance was actually pretty easy using the proxy.  Much easier than configuring networks.

**Comment by Carrotman42** [comment]
That's nice to hear :) thanks for the feedback.
