### ISSUE TITLE
Issues with container version 1.05

### ISSUE THREAD

**Issue by hanzvanaardt** [GoogleCloudPlatform/cloudsql-proxy#329]
Hi there - our company implemented a side-car container using b.gcr.io/cloudsql-docker/gce-proxy:1.05  to access Google Cloud SQL Postgres 11.  The connections failed on Thursday and after troubleshooting we discovered that the sidecar container was no longer able to communicate to Google Cloud SQL Postgres 11 and gave an API error with no details.  Upgrading to version 1.14 resolved the issue.

I need to write a report on the cause of the outing which lasted two hours across all services communicating to Google Cloud SQL using the side car container.  Does anybody have more information on this issue?  Is this a known issue?

**Comment by kurtisvg** [comment]
I'm still looking into this, but unfortunately right now I don't have too much to offer. As far as I can tell, it was limited to the binary compiled for v1.05. Rebuilding the binary from that commit tag does in fact work, which means it's likely limited to a dependency that was used in v1.05. Since this was before Go modules were implemented, it's difficult to reproduce the exact build. 

I'll leave this open for now and update when if I figure anything else out.

**Comment by kurtisvg** [comment]
I spent some more time looking into it but was unable to build a version of the proxy that failed as binary v1.05 did. The other versions seem to still be working fine (as does a more recent build), which points to an issue in a dependency that we're unable to replicate. 

I would suggest updating the proxy semi-frequently (every couple of months) making sure you are on the latest version.

**Comment by hanzvanaardt** [comment]
@kurtisvg - thank you for the update.  I am not sure who the right party is to report this to but this official Google blog ( which guided us and many others ) is then broken due to the issue.  https://cloud.google.com/python/django/kubernetes-engine .  Thank you again for your help - have a great day!

**Comment by kurtisvg** [comment]
@hanzvanaardt Thanks for flagging the page - I've opened an internal bug against it so we can get it corrected.
