### ISSUE TITLE
Unable to connect to MySQL instance with private IP address

### ISSUE THREAD

**Issue by WouterFlorijn** [GoogleCloudPlatform/cloudsql-proxy#342]
Whenever I start the Cloud SQL Proxy, and try to connect to an instance (using mysql cli from another window), I get the following output:

```
$ cloud_sql_proxy -instances=INSTANCE_CONNECTION_STRING=tcp:3310 -ip_address_types=PRIVATE -log_debug_stdout -verbose
2020/01/08 15:02:24 using credential file for authentication; email=SERVICE_ACCOUNT_EMAIL
2020/01/08 15:02:24 Listening on 127.0.0.1:3310 for INSTANCE_CONNECTION_STRING
2020/01/08 15:02:24 Ready for new connections
2020/01/08 15:03:24 New connection for "INSTANCE_CONNECTION_STRING"
2020/01/08 15:03:45 couldn't connect to "INSTANCE_CONNECTION_STRING": dial tcp INSTANCE_IP:3307: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2020/01/08 15:28:16 Received TERM signal. Waiting up to 0s before terminating.
```

I have tried opening up all firewall rules, but nothing changes. I've also tried every suggestion mentioned in #164. According to the logs, the connection does seem to go through and gets authorized, but somehow the proxy doesn't receive the response.

I want to use the proxy to connect to an instance that only has a private IP address from my local machine in order to manage it when necessary. This seems like the intended use of the proxy. However, there is no documentation on this error at all.

Can somebody tell me how to fix it?

**Comment by kurtisvg** [comment]
> I want to use the proxy to connect to an instance that only has a private IP address from my local machine in order to manage it when necessary. This seems like the intended use of the proxy. 

This is incorrect - the Cloud SQL proxy provides IAM authentication only. Connections via private IP must still meet these [requirements ](https://cloud.google.com/sql/docs/mysql/sql-proxy), which include being on the same VPC as the instance. To connect from a device outside the VPC (e.g., your local machine) you can use a public IP instead. 

You can also check out the "[About the Cloud SQL Proxy](https://cloud.google.com/sql/docs/mysql/private-ip#environment_requirements)" page for more information about what the proxy does.

**Comment by WouterFlorijn** [comment]
@kurtisvg does that mean I could run the proxy from a VM/Cloud Run instance in the VPC and then connect from my local machine using the IP of the VM?

**Comment by kurtisvg** [comment]
> @kurtisvg does that mean I could run the proxy from a VM/Cloud Run instance in the VPC and then connect from my local machine using the IP of the VM?

You could run it on a GCE instance (Cloud Run doesn't currently have VPC support AFAIK), but it's almost disadvantageous in every way over just adding a public IP to your instance:

- Connecting with public IP requires some form of auth (proxy, ssl cert, or authorized by IP) to connect while GCE instances don't (by default). You can even make this more secure by _requiring_ connections use the proxy, which means only users with the "Cloud SQL Connect" IAM role or higher can connect to the instance.
- Connecting with public IP should have lower latency since it's a (more) direct connection, instead bouncing off a GCE VM first
- Adding a public IP doesn't cost any more, but having a GCE VM run a proxy likely will
