### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by quinn** [GoogleCloudPlatform/cloudsql-proxy#351]
I ran the cloud proxy, but it did not produce any log output and exited with exit code 1. Is three a way to have it log some output when it exits with exit code 1?

**Comment by kurtisvg** [comment]
Hey @quinn,

The Cloud SQL proxy does output a reason whenever it exits:
```shell
$ ./cloud_sql_proxy
2020/02/13 11:06:01 current FDs rlimit set to 32768, wanted limit is 8500. Nothing to do here.
2020/02/13 11:06:02 unable to retrieve the active gcloud project and -instances and -projects are empty: gcloud has no active project, you can set it by running `gcloud config set project <project>`
```

If you've found a situation where it exits and doesn't print out logs, it would be helpful to include the command you used and steps to reproduce (as well as other information for debugging, such as version number).

Given your comment in #350, it sounds like this is related to trying to run the Cloud SQL proxy in a kubernetes pod. My guess is that your issue is actually unrelated with the proxy, and is something wrong with your pod that is causing it to crash before the container can even start. If you check out that link I googled for you, you'll see you can use `kubectl describe pod POD_NAME` that provides a list of recent events with that proxy:
```shell
Events:
  Type     Reason                 Age               From                                               Message
  ----     ------                 ----              ----                                               -------
  Normal   Scheduled              2m                default-scheduler                                  Successfully assigned nginx-5796d5bc7c-xsl6p to ip-10-0-9-132.us-east-2.compute.internal
  Normal   SuccessfulMountVolume  2m                kubelet, ip-10-0-9-132.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "config"
```

This can provide you with more information about why the pod has failed and entered the `CrashLoopBackOff`.

I'm going to mark this issue as closed now since I'm unable to reproduce the situation and (hopefully) provided you with some helpful feedback, however - if you think I've jumped the gun, feel free to comment on this issue with more information and I'll be happy to reopen and reassess.

**Comment by quinn** [comment]
Thanks for your help 👍
