### ISSUE TITLE
Connection statuses logged as errors

### ISSUE THREAD

**Issue by knation** [GoogleCloudPlatform/cloudsql-proxy#355]
Everything is working fine, but when there are new connections, or client connections are closed, these events are logged as errors, rather than as `INFO`:

```
severity:  "ERROR"  
textPayload:  "2020/02/22 14:21:39 New connection for "<INSTANCE>"
```

```
severity:  "ERROR"  
textPayload:  "2020/02/22 14:21:33 Client closed local connection on 127.0.0.1:3306
```

**Comment by shubha-rajan** [comment]
Hi! This is actually an intentional behavior. #150 implements a flag to override this and log non-error output to Stdout, but it is defaulted to false, as to not break users who are dependent on the existing error logging behavior. If you don't want connection-related messages to log as errors, you can run the proxy with the CLI flag `-log_debug_stdout` explicitly set to true.
