### ISSUE TITLE
macOS proxy won't serve on TCP

### ISSUE THREAD

**Issue by y0ssar1an** [GoogleCloudPlatform/cloudsql-proxy#369]
```bash
> cloud_sql_proxy -credential_file='/path/to/service-account-key.json' -projects='my-project' -instances='my-project:us-central1:main-primary=tcp:5432'
2020/04/05 17:55:05 Rlimits for file descriptors set to {&{8500 9223372036854775807}}
2020/04/05 17:55:05 using credential file for authentication; email=my-service-account@my-project.iam.gserviceaccount.com
2020/04/05 17:55:06 must set -dir: using a unix socket for my-project:us-central1:main-primary
```
On macOS, the proxy won't serve over TCP even with the `=tcp:5432` suffix set. I've tried several different ports, and none of them worked. I've tried running it with and without `sudo`. `cloud_sql_proxy` always falls back to Unix sockets.
```bash
> cloud_sql_proxy -version
Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018
```
I installed it through `gcloud compenents install cloud_sql_proxy` and I'm running macOS 10.15.4.

**Comment by dmahugh** [comment]
Your issue is likely being caused by the use of the -projects flag, which isn't needed for TCP connections and causes the proxy to try to open a socket. Try removing that flag. And if you still have issues, you may want to upgrade to the latest proxy version, 1.16 - https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases

Let me know if that resolves your issue.
