### ISSUE TITLE
Feature Request: Exit 0 on graceful shutdown from SIGTERM

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/cloudsql-proxy#388]
## Feature Description
cloud_sql_proxy currently exits with code 2 after receiving a SIGTERM. I would like it to exit 0 to indicate successful shutdown. This would allow for using SIGTERM to shutdown the proxy in a Kubernetes job after the primary container exits 0 without the job being marked as a failure.

## Alternatives Considered
Another option would be to allow configuring the successful shutdown exit code. This may be more reverse compatible, if required. But the current behavior could also be considered a bug.

**Comment by Carrotman42** [comment]
The current implementation only exits with a nonzero status if there is an error during shutdown; unfortunately, currently that error is not printed out. See https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/389 for a fix for that specific problem.

By my read of the code (https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/3acc260458d1198c32060d20eadfa36cce723a23/proxy/proxy/client.go#L358-L372), the only reason an error would occur is if there are active connections to the Proxy after waiting an amount of time specified by `--term_time`. Note that flag's default value is 0, so if there are any connections at the moment of SIGTERM the Proxy would exit with a nonzero status.

If you expect connections to the Proxy to be torn down "around" the time of the SIGTERM, I suggest setting `--term_time` to some value so that there's time for the Proxy to notice the connections have been closed.

**Comment by karlkfi** [comment]
hmm. The only thing using the proxy was the app (dbmate) that had exited and the liveness/readiness probes (netcat). I had term_time set to 10s, but i can increase it. I'll try to see if I can figure out what's holding open the connections... But thanks for the PR. It'd be nice to know what the failure reason is.

**Comment by karlkfi** [comment]
So it turns out my netcat liveness/readiness probes were leaking open connections.
Changing them to  use `-d` (ignore stdin and FIN immediately) and `-w 5` (timeout before before being killed) solved the issue. cloudsql-proxy now exits 0 on sigterm.
