### ISSUE TITLE
Improve error message when hard rlimit for file descriptors is too low

### ISSUE THREAD

**Issue by mltsy** [GoogleCloudPlatform/cloudsql-proxy#413]
When I run cloud_sql_proxy from my Ubuntu 18.04 VM, it works, but I get this confusing error message every time:

    failed to setup file descriptor limits: failed to set rlimit {&{8500 4096}} for max file descriptors: invalid argument

The root cause of this is that my hard limit for file descriptors available to the process are (for whatever reason) 4096.  In this case, I believe the proxy should try to give the user a more informational error message, rather than trying something that is all but certain to fail, and printing out the inevitable "invalid argument" error.

This is the problem area:
https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/5f761d7ef539bfe4fb65c6856d439496cddbfcc7/proxy/limits/limits.go#L62-L64

I think it's fine to *try* setting the limit in both ways here, but rather than simply outputting whatever error is returned, in the case where we are pretty darn sure it's going to fail, we should set `rLim.Cur = rLim.Max` and output a more helpful message, like "Warning: Hard limit on file descriptors (4096) is lower than the requested fd_rlimit.  This proxy will only be able to handle ~2048 connections. To hide this warning, please use the fd_rlimit flag to request a limit within the available range."

**Comment by mltsy** [comment]
Incidentally, it seems to me that it should not set an fd_rlimit by default, and just display an appropriate warning if it's below a certain level (4000 connections seems like an excessive default to me).  If that were the case, you'd never get the above error message unless you explicitly set an fd_rlimit, in which case you'd know what it was talking about 😄  But at this point, that's a breaking change, I suppose.

**Comment by shubha-rajan** [comment]
Thanks for opening the issue, @mltsy. I agree that the "invalid argument" error isn't very helpful, and a more descriptive error message seems like a simple enough change. As for changing the default behavior, I'm not sure if that would break users or break functionality elsewhere. 

@kurtisvg any thoughts on how to approach this?

**Comment by kurtisvg** [comment]
I think improving the error message sounds like a good idea - I would +1 to messaging similar to "estimated X total number of connections" to  the current "invalid argument" is just what's being returned from the syscall func. One thing to check before removing it completely would be that it always returns "invalid argument" - while this specific error message isn't helpful there might be more other error messages we don't want to conflate.

I'm not sure that removing the the default rLimit is necessarily a breaking change - the overall surface of the API is still the same, even if the default value changes. That said I don't really see any significant benefit from removing it either.

**Comment by mltsy** [comment]
Yeah, the default isn't a big deal - I just feel like users shouldn't get warnings or errors about things that don't matter to them and confuse them or send them on wild goose chases without them enabling some flag or option indicating it's important to them.  But if we just phrase it as you mentioned (not even as a warning) that's a good way to avoid that too - something like "Estimated active connections available: X (see fd_rlimit flag to adjust)"

However, I still think it's necessary to have different message when the user sets the fd_rlimit flag explicitly vs when they don't.  If they set the flag and that limit can't be achieved, it should either exit with an error message, or print a more obvious warning/error message.

**Comment by Carrotman42** [comment]
Note that "invalid argument" comes from the EINVAL return value of setrlimit ([manpage](https://linux.die.net/man/2/setrlimit)). setrlimit can return a bunch of other errors (see manpage), so blindly wrapping the returned error is probably not a good idea. But, verifying the error value before adding additional help text seems appropriate.

Thanks for filing the issue; error messages can usually be improved one way or another so all input is welcome.

> 4000 connections seems like an excessive default to me

I'm a bit confused about this statement; this is the fd *limit*, not any sort of preallocation (right?), so any "reasonable" upper-bound doesn't seem excessive to me since it shouldn't have any overhead on its own. Can you describe if/how this would cause a problem, or in which ways it is inefficient or ineffective to set the limit like this? Perhaps my knowledge is lacking, but I don't see what could go wrong.

As an argument for 4000 being "reasonable": when this code was introduced, 4000 was the absolute max number of connections that a single Cloud SQL database backend was allowed to handle, and it remains the default for most instance shapes. So that seemed like a reasonable value to set as the limit for the client proxy to have that as it's upper limit. (Now that I'm thinking of it, we should need two file descriptors per connection through the proxy, so I admit it's more of an arbitrary choice; please let me know if you have a reason for why the arbitrary limit should be reduced.)

> I'm not sure that removing the the default rLimit is necessarily a breaking change - the overall surface of the API is still the same, even if the default value changes.

While I admit it's not cut and dry about whether this is "breaking", I would definitely consider this a semantic change in functionality due to the fact that there are going to be some people out there who rely on the existing functionality for their application to work correctly. For example, as I understand it, anyone who  holds many concurrent connections through the proxy and relies on the current Proxy functionality of setting this limit (perhaps because there's something else in their system which sets a low soft limit which the Proxy currently overrides) would have their experience degraded. This isn't ideal, and while there can be announcements about this change in the release notes, I'd like to avoid the requirement for everyone to do a special test and a possible config change, at least unless this setting of the fd limit is causing a demonstrable problem.

So, please let us know if this setting of the limit is causing (or could cause) a problem; otherwise it seems like unnecessary toil to the rest of Proxy users to ensure this change gets rolled out safely.

**Comment by mltsy** [comment]
@Carrotman42 I agree, it's really not causing a problem except for when it *appears* to be causing a problem (because its outputting an error message).  So if we resolve that and make it look more like an info message, all is well, in my opinion 🙂

(But again, see above regarding the need for different messaging when the user explicitly sets an fd_rlimit)

**Comment by jefferson-guilherme-machado-barreto** [comment]
I have this error when I try up my server.

I need just change the file description to 8500 1048576?

I change in gcloud or in param on command?

**Comment by kurtisvg** [comment]
@jefferson-guilherme-machado-barreto #609 improved the error message. Are you seeing that error? You may want to upgrade to a new version of the proxy to get the new error.

Setting the `-fd_rlimit` flag when you start the proxy to a better setting should fix the problem.
