### ISSUE TITLE
Cannot Connect to Cloud SQL from Compute Engine via Proxy using PHP/PDO

### ISSUE THREAD

**Issue by syclone** [GoogleCloudPlatform/cloudsql-proxy#42]
I am having an issue connecting to the proxy with PHP/PDO. I followed all the instructions on this page [https://cloud.google.com/sql/docs/compute-engine-access](https://cloud.google.com/sql/docs/compute-engine-access) and I am able to connect with `mysql -u root -p -S /cloudsql/projectid:region:instance` and confirm with `show databases;`. Now my issue when I connect with the PDO I get :

**SQLSTATE[HY000] [2002] Permission denied**

The **DSN** I am trying to connect with is `mysql:unix_socket=/cloudsql/<projectid>:<region>:<instance>;dbname=<dbname>;charset=utf8.` with password.

How did you get this to work with PHP? I am able to confirm that the proxy is connecting in terminal. I am trying to get this to work with PDO running on CentOS. Is this related to [Issue: #7](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/7)?

Thanks

**Comment by Carrotman42** [comment]
It sounds similar to https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/7?

Are you using `-fuse`? I suggest using `-instances` instead. If that also doesn't work then we can look into it more.

**Comment by Carrotman42** [comment]
Are you still having trouble?

**Comment by Carrotman42** [comment]
Please reopen if you have any more thoughts or information for me to help debug.

**Comment by pmothais** [comment]
Hi @syclone, did you find a way to solve this problem? I have exactly the same problem than you and I would like that to explain me how did you fix it please.

Thanks.

**Comment by Carrotman42** [comment]
As suggested in a comment above, did you try just using `-instances`? -fuse
is nice for development but not well tested for longevity.

**Comment by syclone** [comment]
Nothing I tried at the time worked. I switched to just using the IP address
and called it a day. I haven't tried since then. Sorry.

**Comment by pmothais** [comment]
Hi @Carrotman42. Thanks for your answer :)

I tried these two commands :
The first one => ./cloud_sql_proxy -dir=/cloudsql -instances=<INSTANCE_CONNECTION_NAME> &
The second one => ./cloud_sql_proxy -dir=/cloudsql -instances=<INSTANCE_CONNECTION_NAME> -credential_file=<PATH_TO_KEY_FILE> &

But I don't know what is exactly the credential_file.

I'm running on CentOS 7 in a compute engine from Google Cloud Platform. I want to access to one mysql database on the Cloud SQL (from Google Cloud as well). I can access to this one by command line but not with my Laravel application which use PDO.

This command works to connect me on the database directly from my instance :
mysql --ssl-ca=<server-ca.pem> --ssl-cert=<client-cert.pem> --ssl-key=<client-key.pem> --host=<HOST> --user=<USER> --password

Thanks.
Philippe

**Comment by Carrotman42** [comment]
Sorry to hear about your experience. If you ever try again and would like
some assistance, please don't hesitate to open up a new issue explaining
what you tried and what didn't work (along with example code along with any
errors you encountered).

**Comment by Carrotman42** [comment]
Whoops, in my previous message I was confused about who was responding!
Thanks for following up Syclone.

Philippe: have you looked through this documentation? It describes the
credential_file, as well as other options:
https://cloud.google.com/sql/docs/mysql/sql-proxy#authentication-options

On Feb 15, 2018 8:17 AM, "Kevin Malachowski" <notifications@github.com>
wrote:

Sorry to hear about your experience. If you ever try again and would like
some assistance, please don't hesitate to open up a new issue explaining
what you tried and what didn't work (along with example code along with any
errors you encountered).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/42#issuecomment-365978002>,
or mute the thread

**Comment by pmothais** [comment]
@Carrotman42, yes I already read this documentation. But I read is not necessary to use this file if I am connecting to Cloud SQL from a Compute Engine instance. It's the case for me, then the database instance and the compute engine instance are on the same project on Google Cloud Platform.

So for me it's good, I think the proxy is correctly setted up because I can connect me to the database by command line. The problem is when I want to access to the database with my Laravel application, I have the following error :
SQLSTATE[HY000] [2002] Permission denied

I tried everything and I don't know why it still doesn't work :(

Philippe

**Comment by Carrotman42** [comment]
Would you mind opening up a new issue? It's tricky to keep track if we are
chatting on a different issue.

**Comment by syclone** [comment]
@Carrotman42 The issue described by @pmothai sounds exactly same issue.

**Comment by Carrotman42** [comment]
Very sorry for the noise everyone, I agree that they sound similar and that
it might just be better off re-opened instead. Or, if this really is just
another instance of #7 then I'm not sure there's anything we can do for you
right now other than just using the -instances flag.
