### ISSUE TITLE
Documentation missing for log_debug_std flag

### ISSUE THREAD

**Issue by chinmoymohanty85** [GoogleCloudPlatform/cloudsql-proxy#428]
## Description
The CloudSqlProxy README (link below) should have a mention for the flag used to configure the debug messages so that they are piped to stdOut instead of stdErr
https://github.com/GoogleCloudPlatform/cloudsql-proxy#cloud-sql-proxy

## Solution
The documentation should add details about the log_debug_std flag which enables the proper behavior. Since it's by default set as false, the end user is confused as to why normal debug messages are printed as errors in stackdriver logs.

**Comment by chinmoymohanty85** [comment]
Updated documentation for issue #429 not yet merged in master. Re-opening issue

**Comment by shubha-rajan** [comment]
Hi @chinmoymohanty85 , thanks for opening the issue and the PR! PR #150 has some comments which explain the reasoning behind this seemingly non-intuitive behavior. The default logger in the go log package is stderr, and as to not break users who depended on that behavior,  the default for the `log_debug_stdout` flag was set to false.

I agree that it's a good idea to document this since, as you said, many users might be confused and want to override the default. I'll approve and merge your PR.
