### ISSUE TITLE
Allow access to Private IP outside Shared VPC

### ISSUE THREAD

**Issue by sami-tapio** [GoogleCloudPlatform/cloudsql-proxy#432]
## Feature Description

Currently to connect to a Cloud SQL instance using private IP, the proxy must be on a resource with access to the same VPC network as the instance. [1] It would not be possible to connect with a private IP when you are outside the shared VPC network. 
Also it is not possible to configure firewall rules to private IP as it is located in a separate peered VPC managed by Google. There are several use cases in Hybrid and Multi Cloud architectures where Clients are outside of same VPC network as Cloud SQL instance for example in other cloud or onpremises. Enabling Public IP to instance even without authorized networks configured exposes a compliancy and security issue in regulated environments where connectivity need to establish using Private IP connectivity. Can you develop Private IP feature so that it can be accessed outside Shared VPC from other connected networks and controls enabled using GCP native firewalling and access controls. This would allow private hybrid and multi-cloud architecture scenarios for Cloud SQL with Private IP.

[1]https://cloud.google.com/sql/docs/sqlserver/sql-proxy#private-ip

## Alternatives Considered

It is possible to add Public IP to instance without authorized networks to enable connectivity outside Shared VPC using Cloud SQL proxy but this feature is not compliant in all regulated and private hybrid and multi-cloud scenarios.  Also not all applications outside same VPC can utilize Cloud SQL proxy. It is not possible to transfer all clients to same VPC in hybrid and multi-cloud architectures to enable private IP access.

## Additional Context

N/A

**Comment by kurtisvg** [comment]
Hi @sami-tapio,

Thanks for taking the time to open an issue. Unfortunately, this issue is out of scope since this is actually a request for Cloud SQL itself and not anything that can happen within the Cloud SQL proxy. I've passed your feedback to some teams internally, and you are welcome to open a feature request on the [Cloud SQL issue tracker](https://issuetracker.google.com/savedsearches/559773) as well.

> Also it is not possible to configure firewall rules to private IP as it is located in a separate peered VPC managed by Google.

You can use [VPC Egress rules](https://cloud.google.com/vpc/docs/firewalls#egress_cases) to control access to the Cloud SQL instance from your VPC. 

> There are several use cases in Hybrid and Multi Cloud architectures where Clients are outside of same VPC network as Cloud SQL instance for example in other cloud or onpremises

There are instructions on the [Configuring Private IP page](https://cloud.google.com/sql/docs/sqlserver/configure-private-ip#vpn) on how you can configure access via Private IP from a resource that has access to a VPC. 

> Enabling Public IP to instance even without authorized networks configured exposes a compliancy and security issue in regulated environments where connectivity need to establish using Private IP connectivity

Unless you are aware of a vulnerability that I'm not, It is incorrect to state that there is a security issue. Unless you are using authorized IPs, it is not possible to connect directly with the database engine via Public IP - all connections must be authorized by server proxy as described in our [About the Proxy page](https://cloud.google.com/sql/docs/sqlserver/sql-proxy) before they reach the database engine. 

Tangentially, what really makes "private IP" actually private is that access is limited to resources on the VPC. As soon as you begin to circumvent those restrictions to provide access outside the VPC, it's no longer truly private. When you begin talking about cross-cloud VPC connections, at a base level you are (at least, in most scenarios I've experienced) still talking about using authorization and encryption to communicate between two private networks that still trade bits over the public internet. It seems unfair to categorize connections via a public interface as strictly less secure than private interface when in reality the situation is far more nuanced.
