### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by MDrollette** [GoogleCloudPlatform/cloudsql-proxy#44]
When using the proxy with PHP (and no persistent connections) the chattiness of the proxy logs is overwhelming. Since I am running the proxy on Container Engine, those logs are being shipped to Cloud Logging and the amount of "new connection" and "connection closed" messages is significant.

It would be nice to disable logging of new and closed connections.

**Comment by Carrotman42** [comment]
Sure, that makes a lot of sense.

But please note: you really /should/ be pooling connections. Particularly with the proxy, dialing new database connections is significantly less efficient than using existing connections.

**Comment by OlivierBoucher** [comment]
I could submit a pull request if you can tell me which logging library you would like to use.

**Comment by Carrotman42** [comment]
As for what library to use, I would prefer to continue using the standard
logging library in Go. But, it'd be best to abstract it so that users of
the Go library can swap in their own favorite logging library if they feel
like it.

My initial thought is to create a new package `
github.com/GoogleCloudPlatform/cloudsql-proxy/log` which contains exported
variables `Infof`, `Verbosef`, etc which simply forward to the stdlib's
`log.Infof`. In the main file, a "--verbose" flag should be defined, and an
init function should overwrite the definition of `log.Verbosef` to first
check the flag value and then drop the log if the flag is false.

**Comment by OlivierBoucher** [comment]
Thanks, will submit a PR soon

**Comment by OlivierBoucher** [comment]
@Carrotman42 Can you tell me if the current interface suits you? I'm pretty sure it would be compatible with most logging libraries. Just give me a clear and I'll replace references to the stdlib logger in the entire repo

**Comment by mykolasmith** [comment]
https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/100

**Comment by Carrotman42** [comment]
@OlivierBoucher sorry I didn't see your comment from a day ago, and I'm also not exactly sure which interface you mean.

After receiving #100  I went ahead and made the changes I suggested in https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/44#issuecomment-306547267. This will be sent out later today.

**Comment by Carrotman42** [comment]
Setting -verbose=false will now turn off the new/closed connection logs. Note that errors which are not EOF will still be logged when in non-verbose mode since these may be useful for debugging client-/server-side problems. Those who would like to disable all output can use the -quiet flag submitted in #100
