### ISSUE TITLE
Missing container image tag for v1.18

### ISSUE THREAD

**Issue by kyloon** [GoogleCloudPlatform/cloudsql-proxy#467]
The GCR repositories for Cloud SQL Proxy do not have the image tag for v1.18 but has v1.18.0 instead, which is inconsistent with the tag format used in previous versions.

**Comment by kurtisvg** [comment]
Hi @kyloon,

The container images are always tagged with a version matching the release tag on GitHub. We have switched to tagging our releases following a more strict semantic versioning format because it is required for Go modules to work properly and makes it easier for us to release more frequently in the future. We've backdated all of the releases to correctly follow this format, but going forward we won't continue to tag images without a PATCH version.
