### ISSUE TITLE
Doc says Kubernetes needs Service Account but it doesnt

### ISSUE THREAD

**Issue by chrisprobst** [GoogleCloudPlatform/cloudsql-proxy#54]
The docs says that you have to setup a service account and download the json file and use it in the proxy container as secret.

However, when using this on Google Container Engine you actually do not need any service account json file. The Proxy uses the default service account given by the Google Compute Engine Instance the pod is running on. So if the Cloud SQL API is enabled and the container cluster was configured with full access, then there is no need.

Maybe a short info would be helpful :-)

**Comment by Carrotman42** [comment]
Sorry for the late reply. It is the recommendation of Kubernetes to use a credential file instead of relying on the default authentication when running on Google Compute Engine. By using a credential file, you will more easily be able to run your configuration on other clouds or test environments.

I do not think it is worth documenting that it is _possible_ to do this since I think people shouldn't be doing it.

Thank you for raising the issue. Please reopen if you have more concerns!
