### ISSUE TITLE
TLS error causing connection to Cloud SQL proxy to fail

### ISSUE THREAD

**Issue by ouyangz314** [GoogleCloudPlatform/cloudsql-proxy#552]
Hi,

I am from GCP Storage support and one of my customer is experiencing problem using Cloud SQL proxy client library to connect to Cloud SQL proxy. They are running application written in Go in kubernetes pods on GCE instances. The problem started happening on October 12th. Some of their pod (not all of them) would start throwing errors like below:
**local error: tls: bad record MAC**

Customer stated that the errors do not succeed on retry, and at some point the error rate would get too high and they need to restart the problematic pods. When the pods were first created, everything would run without any problems. However, after a few days, after a few days the error would happen again. I have checked on Cloud SQL side. It does not seem like any connection was failing or terminated at time of the incident. I did see that the application was refreshing the ephemeral certificate. Judging by the fact I do not see certification refreshing error, I do not think there was a problem generating the certificate as logic indicated in [1]. Thus, I do not think cloud SQL instance or proxy was behaving weirdly. 

Here is the version they are running with: 
github.com/GoogleCloudPlatform/cloudsql-proxy v1.17.0

Below is the code that was encountering the error:
```
q := db.Select(getJobFields)
	if err := q.Find(&jobs).Error; err != nil {
		return nil, fmt.Errorf("unable to query jobs: %w", err)
	}
```

and 

```

and also 

```
	var tasks []*Task
	err := retry(ctx, func() error {
		tasks = nil
		db := h.db.WithContext(ctx).Where(&Task{JobID: jobID}).Find(&tasks)
		return db.Error
	})
```
An additional detail is that this problem is happening for Cloud Storage client library as well. Please let me know if you need any additional information.

[1] https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/proxy/client.go

**Comment by Carrotman42** [comment]
Clarifying question: Has this situation ever *not* happened, e.g. the Proxy pod could run for many days without seeing this issue before and at some point the issue appeared? I see the issue started October 12 (thanks for that info!), but for how long were they running this setup before that?

Second clarifying question: what is the **full* error error message (stripped of PII)? The full message is integral to debugging this issue. (and hopefully the errors from the Proxy are plumed appropriately).

Since this is happening for the Cloud Storage client library as well, it seems unrelated to the Proxy directly.

After some quick internet searches, that "tls: bad record MAC" error seems to be related to a bad packet checksum in the TLS layer; theories include: low quality network; bad firewall implementation; other man-in-the-middle considerations.

Considering this is GCE I somewhat doubt this is low quality network (between the Pod and the Cloud SQL Database backend), especially since (as reported) the issue goes away on pod restart. That leads me to theorize that something wonky is going on inside the Kubernetes cluster itself, because Kubernetes definitely does some magic with the network from within the cluster.

Has the customer changed the Kubernetes version around the October timeframe? Perhaps there's a bug in a newer version they recently switched to.

Another theory: you say that the customer is using the Proxy Client library in their own Go application; is their Go application intercepting the connections from the Proxy's library somehow and causing havoc?

**Comment by ouyangz314** [comment]
Hi,

I will ask these questions to the customer. 

Regarding your last theory on Go client library, would you elaborate more on your theory? From my understanding, they are making the function call defined by client library (db.select()). Are you suspecting that this call is being overriden by their own function?

**Comment by ouyangz314** [comment]
As for the full message, unfortunately I do not see any additional additional trace. 
This is the full error message from their application log:
"returning internal server error"
**unable to query tasks: local error: tls: bad record MAC**

If you know methods to enable additional debugging logs (I have asked them to enable -log_debug_stdout to capture errors on Proxy and nothing came up), please let me know.

**Comment by Carrotman42** [comment]
> Regarding your last theory on Go client library, would you elaborate more on your theory? From my understanding, they are making the function call defined by client library (db.select()). Are you suspecting that this call is being overriden by their own function?

My suspicion is that they are doing *something* to intercept some connection, and causing trouble. Without access to the codebase there is no way for me to continue debugging this; the customer (or whoever can look at the code) needs to debug this theory. There are lots of ways to break a library if it's being used in an unexpected way. The simplest way to confirm or deny this is to get a minimal reproducer which shows this issue: e.g., can the customer show that this problem exists if they simply use the Client Proxy library in a very-simple application, avoiding as much custom application code as possible? (for example, it just does `SELECT 1` in a loop that triggers every minute or so, but otherwise doesn't do much.) If they can show that happening and can share the code, we are much more likely to be able to debug this train of thought.

>As for the full message, unfortunately I do not see any additional additional trace.
This is the full error message from their application log:
"returning internal server error"
unable to query tasks: local error: tls: bad record MAC

The "unable to query tasks" does not seem to show up in the Cloud SQL Proxy code. From my perspective, there is some missing error information coming out of their application. Without it, and certainly without access to the code, I doubt I could actually help here.

> If you know methods to enable additional debugging logs (I have asked them to enable -log_debug_stdout to capture errors on Proxy and nothing came up), please let me know.

Now I'm confused. The original post says the customer is "using Cloud SQL proxy client library to connect to Cloud SQL proxy". So is the the cloud_sql_proxy pre-built binary being used, or is the proxy client library being used? For example, if one is using the "proxy client library" they must be linking their code to the Go code in this cloudsql-proxy project, and accessing either the [dialer hooks](https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/master/proxy/dialers) or something like the [Client.Dial](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/4a6b3d8c895e2634afd8cee2341db668f20b9a33/proxy/proxy/client.go#L320-L323). But in order to pass any sort of flags on the Proxy they'd have to be using the cloud_sql_proxy binary in some capacity, in which case they definitely shouldn't be using any sort of "proxy client library" in addition.

**Comment by Carrotman42** [comment]
Re-reading everything, I think the customer is not actually using the Cloud SQL proxy client and is instead just using the cloud_sql_proxy binary.

But in that case, I really don't know why tls is coming into play at all: between an application and the cloud_sql_proxy binary there is no TLS at all - it is being sent in the clear because it's expected to be a local/loopback situation, or at least behind a firewall. TLS is only used between the cloud_sql_proxy binary (and the Proxy Client library) and the Cloud SQL backend.

So again, without more error information I really don't think the error seems related to the Cloud SQL Proxy at all. It seems like something wonky with the customer's application.

**Comment by ouyangz314** [comment]
The "unable to query" is a tagged on message from the actual error, sorry for the confusion. 
```
q := db.Select(getJobFields)
	if err := q.Find(&jobs).Error; err != nil {
		return nil, fmt.Errorf("unable to query jobs: %w", err)
	}
```
The customer confirmed that they have recently updated their kubernete to 1.16 (none of other environment setup has changed). 

I will have customer set up the simple test to see if there is any problem with the proxy library they are using
