### ISSUE TITLE
Can't connect to Cloud SQL using Proxy within bash script and cron job

### ISSUE THREAD

**Issue by patcombe** [GoogleCloudPlatform/cloudsql-proxy#563]
## Bug Description

- While running the bash script manually (ie: starting the device and manually running bash run.sh) works fine. 
- Running the bash script using cronjob as the device boots up results in the below error.
- Apologies is this is an error on my part. Just overall very confused on why manually running the .sh file works yet I get the below error. I factored in a 5s wait time as my one hunch was that the device hadn't connected to the internet just yet. 

## Bash Script 

```
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>log.out 2>&1
echo “Started cloud proxy”
echo Before
sleep 5s
echo After

cd /
cd /home/pi/wallflwr_lite/sentinel-scripts
./cloud_sql_proxy -instances=****:****=tcp:1234 -credential_file=../../credentials/DB.json -term_timeout=30s  & 

```

## Stacktrace
```
“Started cloud proxy”
Before
After
2020/12/03 23:01:56 Rlimits for file descriptors set to {&{8500 1048576}}
2020/12/03 23:01:56 using credential file for authentication; email=devicetest2@***-278421.iam.gserviceaccount.com
2020/12/03 23:01:56 errors parsing config:
        Get "https://sqladmin.googleapis.com/sql/v1beta4/projects/***/instances/algorithm-library?alt=json&prettyPrint=false": oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on 192.168.0.1:53: dial udp 192.168.0.1:53: connect: network is unreachable
```

## Environment

1. Raspberry Pi 0 
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.18

**Comment by Carrotman42** [comment]
Instead of a blind sleep, I suggest proactively checking to see if your
network is fully up. My first guess is that it just is taking longer than 5
seconds :) another option is to blindly sleep for 3 minutes; clearly not
ideal, but it can help isolate whether this really is a timing problem or
something deeper.

Looking at the error message, it's failing to connect to DNS on
`192.168.0.1`. Is that the IP address of your home router?

To proactively check for network, you can do something like this:

   while true; do    ping -c 1 192.168.0.1 && break; sleep 10; done

(obviously that wouldn't work "everywhere"; another option is to ping a
public server like 8.8.8.8 (a DNS server run by Google) or some other named
server (e.g. github.com) to check for internet access.)

**Comment by patcombe** [comment]
Thats exactly what I needed, thanks so much! @Carrotman42 . I'll close this issue as it isn't a bug
