### ISSUE TITLE
b.gcr.io deprecation soon

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/cloudsql-proxy#59]
According to https://cloud.google.com/container-registry/docs/support/deprecation-notices, `b.gcr.io` will be deprecated shortly. Can you please start publishing `b.gcr.io/cloudsql-docker` to a different registry?

c.f. https://github.com/kubernetes/test-infra/issues/1670

**Comment by nathanjosiah** [comment]
This will stop working on [February 15](https://cloud.google.com/container-registry/docs/support/deprecation-notices), is there an ETA on this so that projects that are depending on this have time to migrate?

**Comment by Carrotman42** [comment]
We've released a new version available on an updated domain (
gcr.io/cloudsql-docker/gce-proxy:1.06 ), see the releases page. We've also
backfilled the new domain with the images from old releases.

In addition, we've added forwarding rules so that all old URLs correctly
redirect to the new URL. Users are still encouraged to move to the new URL
anyway. I haven't cleaned up the README yet, I don't think, but other docs
should be up to date. Have I missed something?

**Comment by zmerlynn** [comment]
[The front page](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/README.md) still references `b.gcr.io/cloudsql-docker/gce-proxy:1.05`

**Comment by zmerlynn** [comment]
But thank you, I didn't even notice the release, which predates this bug.

**Comment by Carrotman42** [comment]
Yeah that's the readme. I was putting it off since the old URL still will work and I need to update that kubernetes section anyway, but now I've logged on so I can just make the 3 character change (https://github.com/GoogleCloudPlatform/cloudsql-proxy/commit/769672e001a1d71675b8c00bd92ff61d505aef8f)

**Comment by Carrotman42** [comment]
Thanks for the issue, let me know if there's anything else I can help with! And sorry for the initial delay; the issue slipped my radar.

**Comment by zmerlynn** [comment]
Thanks, @Carrotman42!
