### ISSUE TITLE
Tag stable releases in image registry

### ISSUE THREAD

**Issue by tclass** [GoogleCloudPlatform/cloudsql-proxy#708]
## Feature Description
We would like to stay up-to-date with this project but it's not recommend to use "latest" automatically in our build pipeline. Would it be possible to have a "stable" tag in the docker registry which is just 1-2 versions behind which we could use? Then we don't have to update the versions by hand for all services we run and would just use the stable tag.

**Comment by kurtisvg** [comment]
For the same reason it's not recommended to use the "latest" tag, it's not recommended to use any tag that might suddenly change between different versions of a container. If you pin to a tag that might change, you have a dependency that's being updated outside of your control. 

Upgrading dependencies should be a trackable, revertible change that only happens when you decide. There are several tools that can automate proposals for updating dependencies (in this repo we use Renovate) that can trigger your tests and make sure nothing accidentally breaks your build.
