### ISSUE TITLE
Structured logging always logs to stderr

### ISSUE THREAD

**Issue by kundralaci** [GoogleCloudPlatform/cloudsql-proxy#725]
## Bug Description

Now as structured logging has been released, I've tried to use it in combination with the `-log_debug_stdout` flag, so that all log items are structured, and only errors are written to `stderr`. As it turned out, all logs are written to `stderr` if `-structured_logs` is turned on.

## Example command
This command should leave an empty terminal, since `stdout` logs are redirected to `/dev/null`, however `"level":"info"` logs appear in the terminal from `stderr`. 
```
$ ./cloud_sql_proxy.linux.amd64 -verbose=false -credential_file=./secret.json -log_debug_stdout=true -structured_logs=true >/dev/null

{"level":"info","ts":1618224828.160324,"caller":"cloud_sql_proxy/cloud_sql_proxy.go:615","msg":"Ready for new connections"}
```
Also if I pipe `stderr` to `/dev/null` using `2>/dev/null` I get an empty terminal.

## Proposal

Structured logging uses [zap](https://pkg.go.dev/go.uber.org/zap):
```
logger, err := zap.NewProduction()
```
The `NewProduction` uses `stderr` for all logs, as it is declared in its [source](https://github.com/uber-go/zap/blob/404189cf44aea95b0cd9bddcb0242dd4cf88c510/config.go#L120).

I think setting the `OutputPaths` to `[]string{"stdout"}` when `-log_debug_stdout` is set could solve the issue.

## Environment

1. OS type and version: Ubuntu 5.8.0-48-generic x86_64 GNU/Linux
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): Cloud SQL Auth proxy: 1.21.0+linux.amd64

**Comment by enocom** [comment]
Thanks for finding this @kundralaci. The fix is probably a little more involved than seeing the `OutputPaths` field, since that field controls all output (errors included).

Instead, we'll probably want to do something like the [Advanced Configuration](https://pkg.go.dev/go.uber.org/zap#example-package-AdvancedConfiguration) where logging output is sent to stderr or stdout based on priority.

Would you like to try updating your PR to do this? Otherwise, I'm happy to pick this work up myself.

**Comment by kundralaci** [comment]
You're right, thanks for pointing this out!

I'm happy to give it a shot, I'll update the PR soon.
