### ISSUE TITLE
Dialing Freezes

### ISSUE THREAD

**Issue by kevvurs** [GoogleCloudPlatform/cloudsql-proxy#82]
Running dialPassword from a local Go unit test to a 2nd gen. MySQL server. Not a lot different from the example provided in you package. My instance is white-listing all IPv4 connections right now. I have the right username and password. Dies after 3 minutes hang time. Exit status 2, no log.

**Comment by Carrotman42** [comment]
Please share the code you are using so I can help you debug.

**Comment by kevvurs** [comment]
# Solved #
My dumbass forgot about about the strict firewalls on our enterprise network. Went on a public network and it worked quite well. Fantastic job! I recall trying to use Cloud SQL about a year ago with Java 8 in Flexible environment and it had me in tears. This, by comparison was so easy and painless. Thanks guys! Sorry for a false alarm.

**Comment by Carrotman42** [comment]
The difficulty of using Java to connect to Cloud SQL from flex was my fault :/

I didn't understand the complexity of shipping such an app. Due to @laixer 's understanding of the problem, we released https://github.com/GoogleCloudPlatform/cloud-sql-mysql-socket-factory which is a much better solution.
